settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tout les Système sont Operationel'
  notAllmonitorsOperational: 'Les Systeme ne sont pas tous Operationel'
  monitorLabelOperational: 'Operationel'
  monitorLabelNotOperational: 'Non Operationel'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'Tout Operationel'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Site Vitrine # unique identifier
    name: Site Vitrine
    description: '' # default=empty
    url: 'https://eaglecloud.fr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Espace Client
    name: Espace Client
    description: ''
    url: 'https://my.eaglecloud.fr'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Web Panel
    name: Cpanel & Whm
    url: 'https://r5.directdns.com/'
    method: GET
    expectStatus: 200
